# Generated by Django 3.1.7 on 2021-12-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aphorism_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aphorism',
            name='user',
        ),
    ]
